version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/conf/mime.types
      - /etc/letsencrypt/live/ulica.fr/fullchain.pem:/etc/nginx/cert/fullchain-ulica.pem:ro
      - /etc/letsencrypt/live/ulicae.com/fullchain.pem:/etc/nginx/cert/fullchain-ulicae.pem:ro
      - /etc/letsencrypt/live/ulica.fr/privkey.pem:/etc/nginx/cert/privkey-ulica.pem:ro
      - /etc/letsencrypt/live/ulicae.com/privkey.pem:/etc/nginx/cert/privkey-ulicae.pem:ro
      - ./content:/var/www
    network_mode: "host"
